<a href="https://colab.research.google.com/github/sarthak78/COVID-19-Analysis/blob/master/COVID19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
my_list = [[1,2,3], [4,5,6]]
my_list

[[1, 2, 3], [4, 5, 6]]

In [0]:
np.array(my_list)

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
#how to get 500 no. between 0 to 10
#we use linear space function
np.linspace(0,10,500)

In [0]:
arr= np.arange(0,25,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [0]:
#standard deviation
np.std(arr)

7.483314773547883

In [0]:
np.sin(arr)

array([ 0.        ,  0.90929743, -0.7568025 , -0.2794155 ,  0.98935825,
       -0.54402111, -0.53657292,  0.99060736, -0.28790332, -0.75098725,
        0.91294525, -0.00885131, -0.90557836])

In [0]:
np.tan(arr)

array([ 0.        , -2.18503986,  1.15782128, -0.29100619, -6.79971146,
        0.64836083, -0.63585993,  7.24460662,  0.30063224, -1.13731371,
        2.23716094,  0.00885166, -2.1348967 ])

In [0]:
#datset taken was not proper;y framed and was not structured
#to reslove these issues
#use pandas utility
import pandas as pd


In [0]:
COVID19 = pd.read_csv('https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv')

In [0]:
#how to get information of dataset
COVID19.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72988 entries, 0 to 72987
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   date    72988 non-null  object 
 1   county  72988 non-null  object 
 2   state   72988 non-null  object 
 3   fips    72056 non-null  float64
 4   cases   72988 non-null  int64  
 5   deaths  72988 non-null  int64  
dtypes: float64(1), int64(2), object(3)
memory usage: 3.3+ MB


In [0]:
#how to get upper portion 24 rows information
COVID19.head()

date     county       state     fips  cases  deaths
0  2020-01-21  Snohomish  Washington  53061.0      1       0
1  2020-01-22  Snohomish  Washington  53061.0      1       0
2  2020-01-23  Snohomish  Washington  53061.0      1       0
3  2020-01-24       Cook    Illinois  17031.0      1       0
4  2020-01-24  Snohomish  Washington  53061.0      1       0

In [0]:
#graphical representatin of the dataset
#matplotlib
#seaborn: real time support easy
#bokeh: very easy touse
pip install seaborn
#import seaborn as sns

In [0]:
import seaborn as sns

In [0]:
from google.colab import files
uploaded = files.upload()


Saving auto-mpg.csv to auto-mpg.csv


In [0]:
df=pd.read_csv('auto-mpg.csv')

In [0]:
df


mpg  cyl  displ   hp  ...  origin                 name  color  size
0    18.0    6  250.0   88  ...      US         ford mustang   blue  15.0
1     9.0    8  304.0  193  ...      US             hi 1200d   blue  20.0
2    36.1    4   91.0   60  ...    Asia     honda civic cvcc    red  10.0
3    18.5    6  250.0   98  ...      US         ford granada   blue  15.0
4    34.3    4   97.0   78  ...  Europe            audi 4000  green  10.0
..    ...  ...    ...  ...  ...     ...                  ...    ...   ...
387  18.0    6  250.0   88  ...      US        ford maverick   blue  15.0
388  27.0    4  151.0   90  ...      US     chevrolet camaro   blue  10.0
389  29.5    4   98.0   68  ...    Asia      honda accord lx    red  10.0
390  17.5    6  250.0  110  ...      US   chevrolet concours   blue  15.0
391  25.1    4  140.0   88  ...      US  ford fairmont (man)   blue  10.0

[392 rows x 11 columns]

In [0]:
from bokeh.plotting import figure,show 
from bokeh.io import output_notebook
output_notebook()


In [0]:
p=figure (x_axis_label='HP', y_axis_label='MPG')

In [0]:
p

Figure(id='1001', ...)

In [0]:
#how to create circle based application using bokeh
p.circle(df['hp'], df['mpg'], color=df['color'], size=10)

GlyphRenderer(id='1040', ...)

In [0]:
show(p)